/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tudor_android_proxom_ProxyThread */

#ifndef _Included_com_tudor_android_proxom_ProxyThread
#define _Included_com_tudor_android_proxom_ProxyThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tudor_android_proxom_ProxyThread_MIN_PRIORITY
#define com_tudor_android_proxom_ProxyThread_MIN_PRIORITY 1L
#undef com_tudor_android_proxom_ProxyThread_NORM_PRIORITY
#define com_tudor_android_proxom_ProxyThread_NORM_PRIORITY 5L
#undef com_tudor_android_proxom_ProxyThread_MAX_PRIORITY
#define com_tudor_android_proxom_ProxyThread_MAX_PRIORITY 10L
/*
 * Class:     com_tudor_android_proxom_ProxyThread
 * Method:    runProxy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tudor_android_proxom_ProxyThread_runProxy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tudor_android_proxom_ProxyThread
 * Method:    stopProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tudor_android_proxom_ProxyThread_stopProxy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
